//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 10:44:22 AM CET 
//


package com.elidodo.parts.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="yourOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderLineList" type="{http://elidodo.com/parts/ws}orderLineList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "yourOrderNumber",
    "orderLineList"
})
@XmlRootElement(name = "orderPartsRequest")
public class OrderPartsRequest {

    @XmlElement(required = true)
    protected String yourOrderNumber;
    @XmlElement(required = true)
    protected OrderLineList orderLineList;

    /**
     * Gets the value of the yourOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYourOrderNumber() {
        return yourOrderNumber;
    }

    /**
     * Sets the value of the yourOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYourOrderNumber(String value) {
        this.yourOrderNumber = value;
    }

    /**
     * Gets the value of the orderLineList property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLineList }
     *     
     */
    public OrderLineList getOrderLineList() {
        return orderLineList;
    }

    /**
     * Sets the value of the orderLineList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLineList }
     *     
     */
    public void setOrderLineList(OrderLineList value) {
        this.orderLineList = value;
    }

}
