//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 10:44:22 AM CET 
//


package com.elidodo.parts.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eliDodoOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="yourOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderAccepted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="orderLineList" type="{http://elidodo.com/parts/ws}orderLineList"/>
 *         &lt;element name="totalOrderAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="currency" type="{http://elidodo.com/parts/ws}currency"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eliDodoOrderNumber",
    "yourOrderNumber",
    "orderAccepted",
    "orderLineList",
    "totalOrderAmount",
    "currency"
})
@XmlRootElement(name = "orderPartsResponse")
public class OrderPartsResponse {

    @XmlElement(required = true)
    protected String eliDodoOrderNumber;
    @XmlElement(required = true)
    protected String yourOrderNumber;
    protected boolean orderAccepted;
    @XmlElement(required = true)
    protected OrderLineList orderLineList;
    protected double totalOrderAmount;
    @XmlElement(required = true)
    protected Currency currency;

    /**
     * Gets the value of the eliDodoOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEliDodoOrderNumber() {
        return eliDodoOrderNumber;
    }

    /**
     * Sets the value of the eliDodoOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEliDodoOrderNumber(String value) {
        this.eliDodoOrderNumber = value;
    }

    /**
     * Gets the value of the yourOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYourOrderNumber() {
        return yourOrderNumber;
    }

    /**
     * Sets the value of the yourOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYourOrderNumber(String value) {
        this.yourOrderNumber = value;
    }

    /**
     * Gets the value of the orderAccepted property.
     * 
     */
    public boolean isOrderAccepted() {
        return orderAccepted;
    }

    /**
     * Sets the value of the orderAccepted property.
     * 
     */
    public void setOrderAccepted(boolean value) {
        this.orderAccepted = value;
    }

    /**
     * Gets the value of the orderLineList property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLineList }
     *     
     */
    public OrderLineList getOrderLineList() {
        return orderLineList;
    }

    /**
     * Sets the value of the orderLineList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLineList }
     *     
     */
    public void setOrderLineList(OrderLineList value) {
        this.orderLineList = value;
    }

    /**
     * Gets the value of the totalOrderAmount property.
     * 
     */
    public double getTotalOrderAmount() {
        return totalOrderAmount;
    }

    /**
     * Sets the value of the totalOrderAmount property.
     * 
     */
    public void setTotalOrderAmount(double value) {
        this.totalOrderAmount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCurrency(Currency value) {
        this.currency = value;
    }

}
